const seasonalSpirits = {
  Hunter: ["nine_colored_s", "hunter_tree"],
  Princess: ["nine_colored_s", "princess_tree"],
  "Feudal Lord": ["nine_colored_s", "lord_tree"],
  "Herb Gatherer": ["nine_colored_s", "herb_gatherer_tree"],
  "Remenant Of A Forgotten Haven": "forgotten_haven",
  "Echo Of An Abandoned Refuge": "abandoned_refuge",
  "Memory Of A Lost Village": "lost_village",
  "Vestige Of A Deserted Oasis": "deserted_oasis",
  "Nightbird Whisperer": "nightbird",
  "Ascetic Monk": "monk",
  "Jolly Geolist": "geologist",
  "Reassuring Ranger": "ranger",
  "Oddball Outcast": "outcast",
  "Overacting Overachiever": "overachiever",
  "Melancholy Mope": "mope",
  "Tumbling Troublemaker": "troublemaker",
  "Wounded Warrior": "wounded_warrior",
  "Tiptoeing Tea-Brewer": "tea_brewer",
  "Pleading Child": "pleading_child",
  "Bereft Veteran": "veteran",
  "Warrior Of Love": "warrior_of_love",
  "Seed Of Hope": "seed_of_hope",
  "Running Wayfarer": "wayfarer",
  "Mindful Miner": "mindful_miner",
  "Ancient Dark (Plant)": "dark_plant",
  "Ancient Dark (Dragon)": "dark_dragon",
  "Ancient Light (Manta)": "light_manta",
  "Ancient Light (Jelly)": "light_jelly",
  "Modest Dancer": "modest_dancer",
  "Mellow Magician": "mellow_musician",
  "Frantic Stagehand": "stagehand",
  "Forgetful Storyteller": "storyteller",
  "Ceasing Commodore": "commodore",
  "Cackling Cannoneer": "cannoneer",
  "Bumbling Boatswain": "boatswain",
  "Anxious Angler": "angler",
  "Tinkering Chimesmith": "chimesmith",
  "Lively Navigator": "navigator",
  "Light Whisperer": "light_whisperer",
  "Talented Builder": "talented_builder",
  "Stretching Lamplighter": "lamplighter",
  "Star Collector": "star_collector",
  "Sneezing Geographer": "geographer",
  "Slouching Soldier": "slouching_soldier",
  "Gloating Narcissist": "narcissist",
  "Beckoning Ruler": "beckoning_ruler",
  "Scolding Student": "scolding_student",
  "Scaredy Cadet": "cadet",
  "Daydream Forester": "forester",
  "Marching Adventurer": "adventurer",
  "Chuckling Scout": "scout",
  "Baffled Botanist": "botanist",
  "Spinning Mentor": "spinning_mentor",
  "Peeking Postman": "postman",
  "Dancing Performer": "dancing_performer",
  "Bearhug Hermit": "hermit",
  "Prophet Of Fire": "fireprophet",
  "Prophet Of Air": "airprophet",
  "Prophet Of Earth": "earthprophet",
  "Prophet Of Water": "waterprophet",
  "Timid Bookworm": "bookworm",
  "Rallying Thrillseeker": "rallying_thrillseeker",
  "Jelly Whisperer": "jellywhisperer",
  "Hiking Grouch": "grouch",
  "Grateful Shell Collector": "shell_collector",
  "Chill Sunbather": "sunbather",
  "Snoozing Carpenter": "carpenter",
  "Scarecrow Farmer": "scarecrow_farmer",
  "Playfighting Herbalist": "herbalist",
  "Nodding Muralist": "muralist",
  "Indifferent Alchemist": "alchemist",
  "Crab Walker": "crab_walker",
  "Troupe Juggler": "juggler",
  "Troupe Greeter": "greeter",
  "Thoughtful Director": "director",
  "Respectful Pianist": "pianist",
  "Festive Spin Dancer": "spin_dancer",
  "Admiring Actor": "actor",
  "Wise Grandparent": "wise_grandparent",
  "Sparkler Parent": "sparkler_parent",
  "Pleaful Parent": "pleaful_parent",
  "Hairtousle Teen": "hairtousle_teen",
  "Confetti Cousin": "confetti_cousin",
  "Boogie Kid": "boogie_kid",
  "Twirling Champion": "twirling_champion",
  "Shushing Light Scholar": "light_scholar",
  "Piggyback Lightseeker": "piggyback",
  "Laidback Pioneer": "laidback",
  "Doublefive Light Catcher": "light_catcher",
  "Crab Whisperer": "crab_whisperer",
  "Stretching Guru": "stretching",
  "Sassy Drifter": "sassy",
  "Saluting Protector": "saluting",
  "Provoking Performer": "provoking",
  "Leaping Dancer": "leaping",
  "Greeting Shaman": "shaman",
};

const realmsSpirits = {
  "Pointing Candlemaker": "candlemaker",
  "Ushering Stargazer": "stargazer",
  "Rejecting Voyager": "voyager",
  "Applauding Bellmaker": "applauding_bellmaker",
  "Bird Whisperer": "bird_whisperer",
  "Butterfly Charmer": "charmer",
  "Ceremonial Worshiper": "worshiper",
  "Exhausted Dock Worker": "dock_worker",
  "Laughing Light Cather": "laughing_light_catcher",
  "Slumbering Shipwright": "shipwright",
  "Waving Bellmaker": "waving_bellmaker",
  "Apologetic Lumberjack": "lumberjack",
  "Blushing Prospector": "prospector",
  "Dismayed Hunter": "dismayed_hunter",
  "Hide'n'seek Pioneer": "pioneer",
  "Pouty Porter": "porter",
  "Shivering Trailblazer": "trailblazer",
  "Tearful Light Miner": "miner",
  "Whale Whisperer": "whale_whisperer",
  "Backflipping Champion": "backflipping_champion",
  "Bowing Medalist": "medalist",
  "Cheerful Spectator": "spectator",
  "Confident Sightseer": "sightseer",
  "Handstanding Thrillseeker": "handstanding_thrillseeker",
  "Manta Whisperer": "manta_whisperer",
  "Proud Victor": "proud_victor",
  "Courageous Soldier": "courageous_soldier",
  "Fainting Warrior": "fainting_warrior",
  "Frightened Refugee": "refugee",
  "Lookout Scout": "lookout_scout",
  "Saluting Captain": "saluting_captain",
  "Stealthy Survivor": "stealthy_survivor",
  "Levitating Adept": "levitating_adept",
  "Meditating Monastic": "meditating_monastic",
  "Memory Whisperer": "memory_whisperer",
  "Polite Scholar": "polite_scholar",
  "Praying Acolyte": "praying acolyte",
};

module.exports = { seasonalSpirits, realmsSpirits };
