packages:
  - "packages/*"
  - "apps/*"

hoistPattern:
  - "*eslint*"
  - "*prettier*"

publicHoistPattern:
  - "*@nextui-org/*" # https://github.com/pnpm/pnpm/issues/8878#issuecomment-2546442011
  - "*eslint*"
