import {
  ReminderFeatureSchema,
  type ReminderFeature,
  GuildInfoSchema,
  type GuildInfo,
  FeaturesSchema,
  type Features,
  SpiritSchema,
  type SpiritData,
  UserInfoSchema,
  type UserInfo,
  BotStatsSchema,
  type BotStats,
  EventDataSchema,
  type ApiEventData as EventData,
  TSDataSchema,
  type ApiTSData as TSData,
} from "@skyhelperbot/types/api";
