module.exports = {
  'REMENANT OF A FORGOTTEN HAVEN': 'forgotten_haven',
  'ECHO OF AN ABANDONED REFUGE': 'abandoned_refuge',
  'MEMORY OF A LOST VILLAGE': 'lost_village',
  'VESTIGE OF A DESERTED OASIS': 'deserted_oasis',
  'NIGHTBIRD WHISPERER': 'nightbird',
  'ASCETIC MONK': 'monk',
  'JOLLY GEOLIST': 'geologist',
  'REASSURING RANGER': 'ranger',
  'ODDBALL OUTCAST': 'outcast',
  'OVERACTING OVERACHIEVER': 'overachiever',
  'MELANCHOLY MOPE': 'mope',
  'TUMBLING TROUBLEMAKER': 'troublemaker',
  'WOUNDED WARRIOR': 'wounded_warrior',
  'TIPTOEING TEA-BREWER': 'tea_brewer',
  'PLEADING CHILD': 'pleading_child',
  'BEREFT VETERAN': 'veteran',
  'WARRIOR OF LOVE': 'warrior_of_love',
  'SEED OF HOPE': 'seed_of_hope',
  'RUNNING WAYFARER': 'wayfarer',
  'MINDFUL MINER': 'mindful_miner',
  'ANCIENT DARK (PLANT)': 'dark_plant',
  'ANCIENT DARK (DRAGON)': 'dark_dragon',
  'ANCIENT LIGHT (MANTA)': 'light_manta',
  'ANCIENT LIGHT (JELLY)': 'light_jelly',
  'MODEST DANCER': 'modest_dancer',
  'MELLOW MAGICIAN': 'mellow_musician',
  'FRANTIC STAGEHAND': 'stagehand',
  'FORGETFUL STORYTELLER': 'storyteller',
  'CEASING COMMODORE': 'commodore',
  'CACKLING CANNONEER': 'cannoneer',
  'BUMBLING BOATSWAIN': 'boatswain',
  'ANXIOUS ANGLER': 'angler',
  'TINKERING CHIMESMITH': 'chimesmith',
  'LIVELY NAVIGATOR': 'navigator',
  'LIGHT WHISPERER': 'light_whispere',
  'TALENTED BUILDER': 'talented_builder',
  'STRETCHING LAMPLIGHTER': 'lamplighter',
  'STAR COLLECTOR': 'star_collector',
  'SNEEZING GEOGRAPHER': 'geographer',
  'SLOUCHING SOLDIER': 'slouching_soldier',
  'GLOATING NARCISSIST': 'narcissist',
  'BECKONING RULER': 'beckoning_ruler',
  'SCOLDING STUDENT': 'scolding_student',
  'SCAREDY CADET': 'cadet',
  'DAYDREAM FORESTER': 'forester',
  'MARCHING ADVENTURER': 'adventurer',
  'CHUCKLING SCOUT': 'scout',
  'BAFFLED BOTANIST': 'botanist',
  'SPINNING MENTOR': 'spinning_mentor',
  'PEEKING POSTMAN': 'postman',
  'DANCING PERFORMER': 'dancing_performer',
  'BEARHUG HERMIT': 'hermit',
  'PROPHET OF FIRE': 'fireprophet',
  'PROPHET OF AIR': 'airprophet',
  'PROPHET OF EARTH': 'earthprophet',
  'PROPHET OF WATER': 'waterprophet',
  'TIMID BOOKWORM': 'bookworm',
  'RALLYING THRILLSEEKER': 'rallying_thrillseeker',
  'JELLY WHISPERER': 'jellywhisperer',
  'HIKING GROUCH': 'grouch',
  'GRATEFUL SHELL COLLECTOR': 'shell_collector',
  'CHILL SUNBATHER': 'sunbather',
  'SNOOZING CARPENTER': 'carpenter',
  'SCARECROW FARMER': 'scarecrow_farmer',
  'PLAYFIGHTING HERBALIST': 'herbalist',
  'NODDING MURALIST': 'muralist',
  'INDIFFERENT ALCHEMIST': 'alchemist',
  'CRAB WALKER': 'crab_walker',
  'TROUPE JUGGLER': 'juggler',
  'TROUPE GREETER': 'greeter',
  'THOUGHTFUL DIRECTOR': 'director',
  'RESPECTFUL PIANIST': 'pianist',
  'FESTIVE SPIN DANCER': 'spin_dancer',
  'ADMIRING ACTOR': 'actor',
  'WISE GRANDPARENT': 'wise_grandparent',
  'SPARKLER PARENT': 'sparkler_parent',
  'PLEAFUL PARENT': 'pleaful_parent',
  'HAIRTOUSLE TEEN': 'hairtousle_teen',
  'CONFETTI COUSIN': 'confetti_cousin',
  'BOOGIE KID': 'boogie_kid',
  'TWIRLING CHAMPION': 'twirling_champion',
  'SHUSHING LIGHT SCHOLAR': 'light_scholar',
  'PIGGYBACK LIGHTSEEKER': 'piggyback',
  'LAIDBACK PIONEER': 'laidback',
  'DOUBLEFIVE LIGHT CATCHER': 'light_catcher',
  'CRAB WHISPERER': 'crab_whisperer',
  'STRETCHING GURU': 'stretching',
  'SASSY DRIFTER': 'sassy',
  'SALUTING PROTECTOR': 'saluting',
  'PROVOKING PERFORMER': 'provoking',
  'LEAPING DANCER': 'leaping',
  'GREETING SHAMAN': 'shaman',
};
