import type { _Nullable, APIComponentInContainer } from "discord-api-types/v10";

export enum PlannerAction {
  ToggleIAP = "toggle-iap",
  ToggleWL = "toggle-wl",
  ToggleSeasonPass = "toggle-season-pass",
  ToggleFavorite = "toggle-fav",
  UnlockTree = "unlock-tree",
  LockTree = "lock-tree",
  ModifyTree = "modify-tree",
}

export interface NavigationState {
  /** Current page */
  p?: number;

  /** The top level tab it should point to
   * * t = tab
   */
  t: DisplayTabs;

  /** Invoking user's id */
  user: string;

  /** Specific item it should point to
   * * it =item
   */
  it?: string;

  /** Further filter, for example, spirits have `type`, `season`, etc. This is used to navigate there
   * * This is generated by `FilterManager`
   * * f = filter
   */
  f?: string;

  /** Any extra data that are passed
   * * d = data
   */
  d?: string;

  /** Array of values, if it was through a string select.
   * * v = values
   */
  v?: string[];

  /** Options for back button, provided when we want to redirect to somewhere else, instead of generic back
   * For ex, imagine we go to a particular area from wl tab, providing this back btn, we can come back to wl tab
   * * b = back
   */
  b?: _Nullable<Omit<NavigationState, "back" | "user">> | null;

  /** any string to prevent custom_id duplication */
  i?: string;
}

export enum DisplayTabs {
  Home = "h",
  Realms = "r",
  Spirits = "s",
  Seasons = "se",
  Events = "e",
  Items = "i",
  WingedLights = "w",
  Shops = "sh",
  Areas = "a",
}

export interface IPaginatedProps<T> {
  /** Items to paginate */
  items: T[];
  user?: string;

  scrollTo?: (items: T[]) => T;

  /** The current page */
  page?: number;

  /** Override default items per-page (default: `5`) */
  perpage?: number;
  /**
   * The callback that should return container components for each items that is to be displayed
   * @param item The item passed inside the items array
   * @param i Index of the item in the passed array
   */
  itemCallback: (item: T, i: number) => APIComponentInContainer[];
}

// short values to save custom_id spaces
export enum FilterType {
  SpiritTypes = "sp",
  Areas = "ar",
  Realms = "rl",
  Seasons = "sn",
  Events = "ev",
  Order = "o",
  ItemTypes = "it",
  Shops = "shp",
  SpiritTrees = "st",
  Currencies = "cr",
  Highlight = "h",
}
export enum OrderType {
  NameAsc = "name_asc",
  NameDesc = "name_desc",
  DateDesc = "date_desc",
  DateAsc = "date_asc",
}
